# Generated by Django 6.0.3 on 2026-03-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='license_plate',
            field=models.CharField(default=1, max_length=20, verbose_name='رقم اللوحة'),
            preserve_default=False,
        ),
    ]
